# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: google_apps
description: >
  Google Apps Scripts wrapper libraries. These libraries expose the Google
  Apps APIs so they can be used in Dart.
version: 0.1.2
author: Florian Loitsch <florian@loitsch.com>
homepage: https://github.com/google/dart_google_apps

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  js: ^0.6.1
