name: apps_tournament
description: >
  A Google Apps Script program to run tournaments.
  The script handles the creation of brackets, running the event, as
  well as the generation of final reports.
version: 1.0.0
author: Florian Loitsch <florian@loitsch.com>
homepage: https://github.com/google/dart_google_apps

environment:
  sdk: '>=2.3.1 <3.0.0'

dependencies:
  js: ^0.6.1
  ranking: ^0.2.0
  google_apps: ^0.3.0

dev_dependencies:
  test: ^1.6.4
